name: "Issue Commenter"
on:
  issues:
    types: [opened]

jobs:
  comment-on-new-issue:
    runs-on: ubuntu-22.04
    name: Comments for every NEW issue.
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Read issue-comment.md
        id: issue-comment
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        with:
          path: .github/issue-comment.md

      - name: Base comment
        uses: jd-0001/gh-action-comment-on-new-issue@c443e1151cc69b146fd6918cc983ec1bd27ab254
        with:
          message: "${{ steps.issue-comment.outputs.content }}"
          ignore-label: ":anger: prickle"
